### ISSUE TITLE
cannot parse some MIDI files

### ISSUE THREAD

**Issue by kn0ll** [chrisguttandin/midi-json-parser#111] opened 2017-11-18 07:58 UTC
hi Chris, first of all great libraries... solves the issues i had with the others... thank you...

in any case, i had trouble parsing some files. using [MIDIFile test cases](https://github.com/nfroidure/MIDIFile/tree/master/sounds), i tested:

- MIDIOkFormat0.mid 
- MIDIOkFormat1.mid

these two above parse correctly.

- MIDIOkFormat1-lyrics.mid
- MIDIOkFormat2.mid

these two above fail with the following error:

`Uncaught (in promise) Error: Cannot parse a meta event with a type of "1"  at Worker.onMessage`

**Comment by chrisguttandin** [comment] 2017-11-18 20:52
Hi @kn0ll, thanks for reporting that bug, I can confirm that the files can't be parsed. I think it's because they contain a meta event which gets not yet handled at all. I will try to implement the missing functionality.

**Comment by chrisguttandin** [comment] 2017-11-19 02:16
Hi @kn0ll, I just published version [4.1.0](https://www.npmjs.com/package/midi-json-parser). It does now also parse a [IMidiLyricEvent](https://github.com/chrisguttandin/midi-json-parser-worker/blob/master/src/interfaces/midi-lyric-event.ts) or a [IMidiTextEvent](https://github.com/chrisguttandin/midi-json-parser-worker/blob/master/src/interfaces/midi-text-event.ts).

Is it okay that I included the two files which did not work before in this repository to verify that they can be parsed? Can you please also doublecheck that the resulting JSON files are correct. They can be found [here](https://github.com/chrisguttandin/midi-json-parser-worker/blob/master/test/fixtures/MIDIOkFormat2.json) and [here](https://github.com/chrisguttandin/midi-json-parser-worker/blob/master/test/fixtures/MIDIOkFormat1-lyrics.json).

**Comment by kn0ll** [comment] 2017-11-19 19:31
awesome! confirmed it's working on my end. they're not my files, so i can't really give permission. :)

a gentle reminder that `json-midi-message-encoder` is not handling these events yet and will fail trying to encode them.

i wanted to submit a PR for this but i was having some trouble setting a dev env up. linking `json-midi-message-encoder` locally isn't sufficient because it seems like it's compiled into another package...?

**Comment by chrisguttandin** [comment] 2017-11-19 22:32
I created [issue 97](https://github.com/chrisguttandin/json-midi-encoder/issues/97) and [issue 98](https://github.com/chrisguttandin/json-midi-encoder/issues/98) to track the missing encoder implementations.

You're right the actual implementation needs to be done inside the `json-midi-message-encoder` package. If you want to link the package locally you have to run `grunt build` in order to produce the exported JavaScript files. I'm happy to accept pull requests.

Since this issue seems to be resolved I'm closing it now.

**Closed by chrisguttandin** 2017-11-19 22:32 UTC

**Comment by kn0ll** [comment] 2017-11-19 23:59
i tried, but `grunt build` doesn't propagate the changes from `json-midi-message-encoder` to `json-midi-encoder`, which seems to contain it's own copy in [worker.ts](https://github.com/chrisguttandin/json-midi-encoder/blob/master/src/worker/worker.ts)

will dig in later this week. cheers m8

**Comment by chrisguttandin** [comment] 2017-11-21 23:28
Yes, you're right. linking the `json-midi-message-encoder` to `json-midi-encoder` is not possible. `json-midi-encoder` is a convenient version of the `json-midi-encoder-broker` which expects an instance of a `json-midi-encoder-worker`.

That's a lot of ceremony, but it ensures that the `json-midi-encoder` can be used without thinking about WebWorkers.

**Comment by chrisguttandin** [comment] 2017-11-26 18:24
Hi @kn0ll, I finally found some time to make the lyric and text events encodable. Please let me know if you encounter another unparsable file.
